# Generated by Django 5.2.9 on 2025-12-11 11:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssortmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Группа ассортимента')),
            ],
            options={
                'verbose_name': 'группа ассортимента',
                'verbose_name_plural': 'Группы ассортимента',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('correspondent_account_number', models.CharField(max_length=20, verbose_name='Номер корреспондентского счёта')),
                ('bank_identification_code', models.CharField(max_length=9, verbose_name='БИК')),
                ('taxpayer_identification_number', models.CharField(max_length=10, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'Города',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'классификация',
                'verbose_name_plural': 'Классификации',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата поставки')),
            ],
            options={
                'verbose_name': 'поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'структурное подразделение',
                'verbose_name_plural': 'Структурные подразделения',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'подразделение предприятия',
                'verbose_name_plural': 'Подразделения предприятия',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес брутто')),
                ('net_weight', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Вес нетто')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код по ОКПДТР')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('price_premium', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ценовая надбавка (в %)')),
                ('remaining_stock', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток на складе')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Закупочная цена')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата отчёта по реализации')),
            ],
            options={
                'verbose_name': 'отчёт по реализации',
                'verbose_name_plural': 'Отчёты по реализации',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'улица',
                'verbose_name_plural': 'Улицы',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('output', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Выход')),
                ('description', models.TextField(verbose_name='Краткое описание приготовления')),
                ('image', models.ImageField(null=True, upload_to='dishes/', verbose_name='Фото')),
                ('assortment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assortmentgroup', verbose_name='Группа ассортимента')),
                ('ingredients', models.ManyToManyField(to='core.ingredient', verbose_name='Ингредиенты')),
                ('unit_of_measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unitofmeasurement', verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'Блюда',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'продукт в поставке',
                'verbose_name_plural': 'Продукты в поставке',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('code', models.CharField(max_length=8, verbose_name='Код по ОК')),
                ('abbreviation', models.CharField(choices=[('ООО', 'Ooo'), ('АО', 'Ao'), ('ИП', 'Ip'), ('ПАО', 'Pao'), ('ПК', 'Pk'), ('КПКГ', 'Kpkg'), ('ГУП', 'Gup'), ('МУП', 'Mup'), ('ФКП', 'Fkp'), ('НКО', 'Nko')], max_length=20)),
                ('account_number', models.CharField(max_length=30, verbose_name='Номер расчётного счёта')),
                ('director_first_name', models.CharField(max_length=25, verbose_name='Имя руководителя')),
                ('director_last_name', models.CharField(max_length=25, verbose_name='Фамилия руководителя')),
                ('director_phone', models.CharField(max_length=25, verbose_name='Номер телефона руководителя')),
                ('house_number', models.CharField(max_length=6, verbose_name='Номер дома')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bank', verbose_name='Банк')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Поставщик'),
        ),
        migrations.CreateModel(
            name='ReportDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dish', verbose_name='Блюдо')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.report', verbose_name='Отчёт по реализации')),
            ],
            options={
                'verbose_name': 'блюдо в отчёте',
                'verbose_name_plural': 'Блюда в отчёте',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата заявки')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.division')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Продукт')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.request', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'продукт в заявке',
                'verbose_name_plural': 'Продукты в заявке',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'место работы',
                'verbose_name_plural': 'Места работы',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=25, verbose_name='Отчество')),
                ('birthday_date', models.DateTimeField(verbose_name='День рождения')),
                ('house_number', models.CharField(max_length=6, verbose_name='Номер дома')),
                ('work_experience', models.CharField(max_length=20, verbose_name='Трудовой стаж')),
                ('gender', models.CharField(choices=[('Мужской', 'Male'), ('Женский', 'Female')], max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city', verbose_name='Город')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country', verbose_name='Страна')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.position', verbose_name='Должность')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['-last_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unitofmeasurement', verbose_name='Единицы измерения'),
        ),
        migrations.CreateModel(
            name='WorkBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(null=True, verbose_name='Дата записи')),
                ('reason_for_dismissal', models.TextField(null=True, verbose_name='Причина прекращения ТД')),
                ('event_type', models.CharField(choices=[('Прием', 'Hiring'), ('Увольнение', 'Dismissal'), ('Перевод', 'Transfer')], max_length=20)),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('document_type', models.CharField(max_length=30, verbose_name='Тип документа')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classification', verbose_name='Классификация')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='Структурное подразделение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Работник')),
                ('place_of_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.placeofwork', verbose_name='Место работы')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profession', verbose_name='Профессия')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'запись в трудовой книге',
                'verbose_name_plural': 'Записи в трудовой книге',
                'ordering': ['-event_date'],
            },
        ),
    ]
