# Generated by Django 4.2.27 on 2025-12-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday_date',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(verbose_name='Дата отчёта по реализации'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='event_date',
            field=models.DateField(null=True, verbose_name='Дата записи'),
        ),
    ]
