# Generated by Django 4.2.27 on 2025-12-14 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_delivery_date_alter_employee_birthday_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('create', 'Создание записи'), ('update', 'Изменение записи'), ('delete', 'Удаление записи'), ('view', 'Просмотр таблицы'), ('download', 'Скачивание файла'), ('export', 'Экспорт данных'), ('import', 'Импорт данных'), ('print', 'Печать')], max_length=20, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('object_name', models.CharField(max_length=200, verbose_name='Название объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Дополнительные сведения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'действие пользователя',
                'verbose_name_plural': 'Действия пользователей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
