# Generated by Django 4.2.27 on 2025-12-15 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(default='', verbose_name='Краткое описание приготовления'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='output',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='abbreviation',
            field=models.CharField(choices=[('ООО', 'Ooo'), ('АО', 'Ao'), ('ИП', 'Ip'), ('ПАО', 'Pao'), ('ПК', 'Pk'), ('КПКГ', 'Kpkg'), ('ГУП', 'Gup'), ('МУП', 'Mup'), ('ФКП', 'Fkp'), ('НКО', 'Nko')], default='ООО', max_length=20),
        ),
    ]
