# Generated by Django 4.2.27 on 2025-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dish_description_alter_dish_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Male'), ('Женский', 'Female'), ("<class 'core.models.GenderType.Meta'>", 'Meta')], max_length=40),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='event_type',
            field=models.CharField(choices=[('Прием', 'Hiring'), ('Увольнение', 'Dismissal'), ('Перевод', 'Transfer'), ("<class 'core.models.EventType.Meta'>", 'Meta')], max_length=40),
        ),
    ]
